CREATE DATABASE IF NOT EXISTS mySlimDB;
USE mySlimDB;

CREATE TABLE Users (
 Id INT NOT NULL AUTO_INCREMENT,
 Username VARCHAR(255) NOT NULL UNIQUE,
 Password VARCHAR(255) NOT NULL,
 PRIMARY KEY (id));